version: '3.8'

services:
  # ----------------------------------------
  # 1. SERVIÇO DO MONGODB
  # ----------------------------------------
  mongo-db:
    image: mongo:4.4
    container_name: mongodb_data
    restart: always
    # Não precisa de porta exposta para o host, apenas para o backend
    # ports:
    #   - "27017:27017" 
    
    environment:
      # Credenciais ROOT do MongoDB (use valores seguros!)
      MONGO_INITDB_ROOT_USERNAME: userroot
      MONGO_INITDB_ROOT_PASSWORD: senhasegura
      # Nome do banco de dados padrão para a aplicação
      MONGO_INITDB_DATABASE: portifolio_db
      
    volumes:
      # Persistência de dados: Mapeia o volume para manter os dados após o restart
      - mongodb_data:/data/db

  # ----------------------------------------
  # 2. SERVIÇO DO BACKEND (Node.js/Express)
  # ----------------------------------------
  backend:
    build: 
      context: ./backend # Caminho para a pasta do seu backend
      dockerfile: Dockerfile
    container_name: portifolio_backend
    restart: always
    
    # EXPOSIÇÃO DE PORTAS: Acessível via http://localhost:2100 no seu host
    ports:
      - "2100:2100" 
      
    environment:
      # Variáveis de conexão do backend (Node.js)
      # Host usa o nome do serviço Docker: mongo-db
      MONGO_URI: mongodb://userroot:senhasegura@mongo-db:27017/portifolio_db?authSource=admin
      PORT: 2100

    depends_on:
      - mongo-db # Garante que o banco suba primeiro

  # ----------------------------------------
  # 3. SERVIÇO DO FRONTEND (React/Nginx)
  # ----------------------------------------
  frontend:
    build:
      context: ./template-portifolio # Caminho para a pasta do seu frontend
      dockerfile: Dockerfile.frontend
    container_name: portifolio_frontend
    restart: always
    
    # EXPOSIÇÃO DE PORTAS: Acessível via http://localhost no seu host
    ports:
      - "80:80" 
      
    environment:
      # VARIÁVEL CRUCIAL AJUSTADA:
      # O navegador (no host) acessa o backend via localhost e a porta exposta (2100)
      REACT_APP_API_URL: http://localhost:2100
      
    depends_on:
      - backend # Garante que o backend suba primeiro

# ----------------------------------------
# VOLUMES (Para persistência do MongoDB)
# ----------------------------------------
volumes:
  mongodb_data:
    driver: local